const now = Date.now();

export const MAIL = [
  {
    id: "e1",
    folder: "Inbox",
    fromName: "CEO",
    fromEmail: "boss@company.com",
    subject: "Quarterly deck review",
    snippet: "Sharing slides. Need notes by EOD tomorrow.",
    receivedISO: new Date(now - 1 * 60 * 60 * 1000).toISOString(),
    ttl: 24,
    unread: true,
    starred: true,
    labels: ["Work"],
    body: "Attaching the Q3 deck. Please leave comments on slides 7–12.",
  },
  {
    id: "e2",
    folder: "Inbox",
    fromName: "HR",
    fromEmail: "hr@company.com",
    subject: "Benefits enrollment",
    snippet: "Open enrollment closes Friday.",
    receivedISO: new Date(now - 12 * 60 * 60 * 1000).toISOString(),
    ttl: 24,
    unread: true,
    starred: false,
    labels: ["Admin"],
    body: "Reminder: Open enrollment ends at 5pm Friday.",
  },
  {
    id: "e3",
    folder: "Inbox",
    fromName: "Meet",
    fromEmail: "noreply@meet.com",
    subject: "Invite: Product sync",
    snippet: "Tue 2:00–2:45pm. Agenda attached.",
    receivedISO: new Date(now - 36 * 60 * 60 * 1000).toISOString(),
    ttl: 48,
    unread: false,
    starred: false,
    labels: ["Meetings"],
    body: "Agenda: roadmap, risks, launch date.",
  },
];
